CREATE TABLE IF NOT EXISTS Genres(
	ID SERIAL PRIMARY KEY,
	name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Singers(
	ID SERIAL PRIMARY KEY,
	name VARCHAR(255) UNIQUE NOT NULL,
	genre INTEGER 
);

CREATE TABLE IF NOT EXISTS SingerGenre(
	SingerID INTEGER REFERENCES Singers(ID),
	GenreID INTEGER REFERENCES Genres(ID),
	CONSTRAINT pk PRIMARY KEY (SingerID, GenreID)
);

CREATE TABLE IF NOT EXISTS Albums(
	ID SERIAL PRIMARY KEY,
	title VARCHAR(255) UNIQUE NOT NULL,
	year INTEGER 
);

CREATE TABLE IF NOT EXISTS AlbumSinger(
	AlbumID INTEGER REFERENCES Albums(ID),
	SingerID INTEGER REFERENCES Singers(ID),
	CONSTRAINT pk1 PRIMARY KEY (ALbumID, SingerID)
);

CREATE TABLE IF NOT EXISTS Songs(
	ID SERIAL PRIMARY KEY,
	Album_ID INTEGER NOT NULL REFERENCES Albums(ID),
	name VARCHAR(255) UNIQUE NOT NULL,
	year INTEGER
);

CREATE TABLE IF NOT EXISTS Collections(
	ID SERIAL PRIMARY KEY,
	name VARCHAR(255) UNIQUE NOT NULL,
	year INTEGER 
);

CREATE TABLE IF NOT EXISTS CollectionSong(
	CollectionID INTEGER REFERENCES Collections(ID),
	SongID INTEGER REFERENCES Songs(ID),
	CONSTRAINT pk2 PRIMARY KEY (CollectionID, SongID)
);

ALTER TABLE songs
ADD COLUMN duration TIME;





